package com.virtubil.init.beans;
// Generated Feb 9, 2017 11:21:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Court generated by hbm2java
 */
@Entity
@Table(name="court"
    ,catalog="diary"
)
public class Court  implements java.io.Serializable {


     private Integer courtId;
     private String name;
     private Set<Cases> caseses = new HashSet<Cases>(0);

    public Court() {
    }

    public Court(String name, Set<Cases> caseses) {
       this.name = name;
       this.caseses = caseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="courtID", unique=true, nullable=false)
    public Integer getCourtId() {
        return this.courtId;
    }
    
    public void setCourtId(Integer courtId) {
        this.courtId = courtId;
    }

    
    @Column(name="name", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="court")
    public Set<Cases> getCaseses() {
        return this.caseses;
    }
    
    public void setCaseses(Set<Cases> caseses) {
        this.caseses = caseses;
    }




}


