package com.virtubil.init.beans;
// Generated Feb 9, 2017 11:21:33 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Defendant generated by hbm2java
 */
@Entity
@Table(name="defendant"
    ,catalog="diary"
)
public class Defendant  implements java.io.Serializable {


     private Integer defendantId;
     private Cases cases;
     private String firstName;
     private String lastName;
     private String address;
     private String mobile;

    public Defendant() {
    }

    public Defendant(Cases cases, String firstName, String lastName, String address, String mobile) {
       this.cases = cases;
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.mobile = mobile;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="defendantID", unique=true, nullable=false)
    public Integer getDefendantId() {
        return this.defendantId;
    }
    
    public void setDefendantId(Integer defendantId) {
        this.defendantId = defendantId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="caseID")
    public Cases getCases() {
        return this.cases;
    }
    
    public void setCases(Cases cases) {
        this.cases = cases;
    }

    
    @Column(name="firstName", length=20)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", length=20)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address", length=2000)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="mobile", length=15)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }




}


