package com.virtubil.init.beans;
// Generated Feb 9, 2017 11:21:33 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Document generated by hbm2java
 */
@Entity
@Table(name="document"
    ,catalog="diary"
)
public class Document  implements java.io.Serializable {


     private Integer documentId;
     private Cases cases;
     private String description;
     private Boolean isOriginal;
     private Date receivedDate;
     private Date filedInCourtDate;
     private Date returnedDate;

    public Document() {
    }

    public Document(Cases cases, String description, Boolean isOriginal, Date receivedDate, Date filedInCourtDate, Date returnedDate) {
       this.cases = cases;
       this.description = description;
       this.isOriginal = isOriginal;
       this.receivedDate = receivedDate;
       this.filedInCourtDate = filedInCourtDate;
       this.returnedDate = returnedDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="documentID", unique=true, nullable=false)
    public Integer getDocumentId() {
        return this.documentId;
    }
    
    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="caseID")
    public Cases getCases() {
        return this.cases;
    }
    
    public void setCases(Cases cases) {
        this.cases = cases;
    }

    
    @Column(name="description", length=2000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="isOriginal")
    public Boolean getIsOriginal() {
        return this.isOriginal;
    }
    
    public void setIsOriginal(Boolean isOriginal) {
        this.isOriginal = isOriginal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="receivedDate", length=10)
    public Date getReceivedDate() {
        return this.receivedDate;
    }
    
    public void setReceivedDate(Date receivedDate) {
        this.receivedDate = receivedDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="filedInCourtDate", length=10)
    public Date getFiledInCourtDate() {
        return this.filedInCourtDate;
    }
    
    public void setFiledInCourtDate(Date filedInCourtDate) {
        this.filedInCourtDate = filedInCourtDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="returnedDate", length=10)
    public Date getReturnedDate() {
        return this.returnedDate;
    }
    
    public void setReturnedDate(Date returnedDate) {
        this.returnedDate = returnedDate;
    }




}


