package com.virtubil.init.beans;
// Generated Feb 9, 2017 11:21:33 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name="type"
    ,catalog="diary"
)
public class Type  implements java.io.Serializable {


     private Integer typeId;
     private String name;
     private Set<Cases> caseses = new HashSet<Cases>(0);

    public Type() {
    }

    public Type(String name, Set<Cases> caseses) {
       this.name = name;
       this.caseses = caseses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="typeID", unique=true, nullable=false)
    public Integer getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="type")
    public Set<Cases> getCaseses() {
        return this.caseses;
    }
    
    public void setCaseses(Set<Cases> caseses) {
        this.caseses = caseses;
    }




}


