package com.virtubil.common.application.beans;
// Generated Feb 9, 2017 11:21:33 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client",
         catalog = "diary"
)
public class Client implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "clientID", unique = true, nullable = false)
    private Integer clientId;
    
    @Column(name = "firstName", length = 20)
    private String firstName;
    
    @Column(name = "lastName", length = 20)
    private String lastName;
    
    @Column(name = "address", length = 2000)
    private String address;
    
    @Column(name = "mobile", length = 15)
    private String mobile;
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
    private Set<RelationCasesClient> relationCasesClients = new HashSet<RelationCasesClient>(0);

    public Client() {
    }

    public Client(String firstName, String lastName, String address, String mobile, Set<RelationCasesClient> relationCasesClients) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.mobile = mobile;
        this.relationCasesClients = relationCasesClients;
    }

    public Integer getClientId() {
        return this.clientId;
    }

    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public Set<RelationCasesClient> getRelationCasesClients() {
        return this.relationCasesClients;
    }

    public void setRelationCasesClients(Set<RelationCasesClient> relationCasesClients) {
        this.relationCasesClients = relationCasesClients;
    }

}
