package com.virtubil.common.application.beans;
// Generated Feb 9, 2017 11:21:33 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RelationCasesClient generated by hbm2java
 */
@Entity
@Table(name = "relation_cases_client",
         catalog = "diary"
)
public class RelationCasesClient implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "relationID", unique = true, nullable = false)
    private Integer relationId;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "caseID", nullable = false)
    private Cases cases;
    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "clientID", nullable = false)
    private Client client;

    public RelationCasesClient() {
    }

    public RelationCasesClient(Cases cases, Client client) {
        this.cases = cases;
        this.client = client;
    }

    public Integer getRelationId() {
        return this.relationId;
    }

    public void setRelationId(Integer relationId) {
        this.relationId = relationId;
    }

    public Cases getCases() {
        return this.cases;
    }

    public void setCases(Cases cases) {
        this.cases = cases;
    }

    public Client getClient() {
        return this.client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

}
